### ISSUE TITLE
Melhorar configuracao de conexao com mongodb

### ISSUE THREAD

**Issue by leoelias023** [leoelias023/client-ifoodapi#1]
Adicionar validacoes necessarias para validar se as variaveis de ambiente com credenciais do mongodb estão configuradas antes de realizar conexao, para evitar erros genericos.

```
MongoError: Authentication failed.
    at MessageStream.messageHandler (/home/leo/workspace/leo/client-ifoodapi/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:314:20)
    at processIncomingData (/home/leo/workspace/leo/client-ifoodapi/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/leo/workspace/leo/client-ifoodapi/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.ondata (_stream_readable.js:713:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError'
} Database not connected...

```

**Comment by leoelias023** [comment]
Extrair endereco de cluster da url-strng do mongo para variavel de ambiente... :+1:
